/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'discountPrice' : [] | [bigint],
  'price' : bigint,
}
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'productName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  '_init' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[string, string, bigint, string], Review>,
  'addToCart' : ActorMethod<[string, bigint, bigint], boolean>,
  'clearCart' : ActorMethod<[string], boolean>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'removeFromCart' : ActorMethod<[string, bigint], boolean>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactSubmission
  >,
  'updateCartQuantity' : ActorMethod<[string, bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];