/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'productName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'discountPrice' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_init' : IDL.Func([], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [Review], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'clearCart' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
  'updateCartQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'productName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'discountPrice' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_init' : IDL.Func([], [], []),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Review],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'clearCart' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
    'updateCartQuantity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };